targets:
  $default:
    builders:
      json_serializable:
        generate_for:
          - "lib/**"
          - "modules/**"
    sources:
      - $package$
      - "lib/**"
      - "test/**"
      - "modules/**"